apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: armdocker.rnd.ericsson.se/dockerhub-ericsson-remote/schoolofdevops/vote:v3
        name: vote
